export const skills = {
  "Astrogation": { value: "Astrogation", label: "SWFFG.SkillsNameAstrogation", abrev: "SWFFG.SkillsNameAstrogation" },
  "Athletics": { value: "Athletics", label: "SWFFG.SkillsNameAthletics", abrev: "SWFFG.SkillsNameAthletics" },
  "Brawl": { value: "Brawl", label: "SWFFG.SkillsNameBrawl", abrev: "SWFFG.SkillsNameBrawlAbbreviation" },
  "Charm": { value: "Charm", label: "SWFFG.SkillsNameCharm", abrev: "SWFFG.SkillsNameCharm" },
  "Coercion": { value: "Coercion", label: "SWFFG.SkillsNameCoercion", abrev: "SWFFG.SkillsNameCoercion" },
  "Computers": { value: "Computers", label: "SWFFG.SkillsNameComputers", abrev: "SWFFG.SkillsNameComputers" },
  "Cool": { value: "Cool", label: "SWFFG.SkillsNameCool", abrev: "SWFFG.SkillsNameCool" },
  "Coordination": { value: "Coordination", label: "SWFFG.SkillsNameCoordination", abrev: "SWFFG.SkillsNameCoordination" },
  "Deception": { value: "Deception", label: "SWFFG.SkillsNameDeception", abrev: "SWFFG.SkillsNameDeception" },
  "Discipline": { value: "Discipline", label: "SWFFG.SkillsNameDiscipline", abrev: "SWFFG.SkillsNameDiscipline" },
  "Gunnery": { value: "Gunnery", label: "SWFFG.SkillsNameGunnery", abrev: "SWFFG.SkillsNameGunneryAbbreviation" },
  "Knowledge: Core Worlds": { value: "Knowledge: Core Worlds", label: "SWFFG.SkillsNameKnowledgeCoreWorlds", abrev: "SWFFG.SkillsNameKnowledgeCoreWorldsStripped" },
  "Knowledge: Education": { value: "Knowledge: Education", label: "SWFFG.SkillsNameKnowledgeEducation", abrev: "SWFFG.SkillsNameKnowledgeEducationStripped" },
  "Knowledge: Lore": { value: "Knowledge: Lore", label: "SWFFG.SkillsNameKnowledgeLore", abrev: "SWFFG.SkillsNameKnowledgeLoreStripped" },
  "Knowledge: Outer Rim": { value: "Knowledge: Outer Rim", label: "SWFFG.SkillsNameKnowledgeOuterRim", abrev: "SWFFG.SkillsNameKnowledgeOuterRimStripped" },
  "Knowledge: Underworld": { value: "Knowledge: Underworld", label: "SWFFG.SkillsNameKnowledgeUnderworld", abrev: "SWFFG.SkillsNameKnowledgeUnderworldStripped" },
  "Knowledge: Warfare": { value: "Knowledge: Warfare", label: "SWFFG.SkillsNameKnowledgeWarfare", abrev: "SWFFG.SkillsNameKnowledgeWarfareStripped" },
  "Knowledge: Xenology": { value: "Knowledge: Xenology", label: "SWFFG.SkillsNameKnowledgeXenology", abrev: "SWFFG.SkillsNameKnowledgeXenologyStripped" },
  "Leadership": { value: "Leadership", label: "SWFFG.SkillsNameLeadership", abrev: "SWFFG.SkillsNameLeadership" },
  "Lightsaber": { value: "Lightsaber", label: "SWFFG.SkillsNameLightsaber", abrev: "SWFFG.SkillsNameLightsaberAbbreviation" },
  "Mechanics": { value: "Mechanics", label: "SWFFG.SkillsNameMechanics", abrev: "SWFFG.SkillsNameMechanics" },
  "Medicine": { value: "Medicine", label: "SWFFG.SkillsNameMedicine", abrev: "SWFFG.SkillsNameMedicine" },
  "Melee": { value: "Melee", label: "SWFFG.SkillsNameMelee", abrev: "SWFFG.SkillsNameMeleeAbbreviation" },
  "Negotiation": { value: "Negotiation", label: "SWFFG.SkillsNameNegotiation", abrev: "SWFFG.SkillsNameNegotiation" },
  "Perception": { value: "Perception", label: "SWFFG.SkillsNamePerception", abrev: "SWFFG.SkillsNamePerception" },
  "Piloting: Planetary": { value: "Piloting: Planetary", label: "SWFFG.SkillsNamePilotingPlanetary", abrev: "SWFFG.SkillsNamePilotingPlanetary" },
  "Piloting: Space": { value: "Piloting: Space", label: "SWFFG.SkillsNamePilotingSpace", abrev: "SWFFG.SkillsNamePilotingSpace" },
  "Ranged: Heavy": { value: "Ranged: Heavy", label: "SWFFG.SkillsNameRangedHeavy", abrev: "SWFFG.SkillsNameRangedHeavyAbbreviation" },
  "Ranged: Light": { value: "Ranged: Light", label: "SWFFG.SkillsNameRangedLight", abrev: "SWFFG.SkillsNameRangedLightAbbreviation" },
  "Resilience": { value: "Resilience", label: "SWFFG.SkillsNameResilience", abrev: "SWFFG.SkillsNameResilience" },
  "Skulduggery": { value: "Skulduggery", label: "SWFFG.SkillsNameSkulduggery", abrev: "SWFFG.SkillsNameSkulduggery" },
  "Stealth": { value: "Stealth", label: "SWFFG.SkillsNameStealth", abrev: "SWFFG.SkillsNameStealth" },
  "Streetwise": { value: "Streetwise", label: "SWFFG.SkillsNameStreetwise", abrev: "SWFFG.SkillsNameStreetwise" },
  "Survival": { value: "Survival", label: "SWFFG.SkillsNameSurvival", abrev: "SWFFG.SkillsNameSurvival" },
  "Vigilance": { value: "Vigilance", label: "SWFFG.SkillsNameVigilance", abrev: "SWFFG.SkillsNameVigilance" },
  "AT-Field": { value: "AT-Field", label: "SWFFG.SkillsNameATField", abbrev: "SWFFG.SkillsNameATField" },
  "Focus": { value: "Focus", label: "SWFFG.SkillsNameFocus", abbrev: "SWFFG.SkillsNameFocus" },
  "Operating": { value: "Operating", label: "SWFFG.SkillsNameOperating", abbrev: "SWFFG.SkillsNameOperating" },
  "Piloting": { value: "Piloting", label: "SWFFG.SkillsNamePiloting", abbrev: "SWFFG.SkillsNamePiloting" },
  "Synchronization": { value: "Synchronization", label: "SWFFG.SkillsNameSynchronization", abbrev: "SWFFG.SkillsNameSynchronization" },
  "Knowledge: Engineering": { value: "Knowledge: Engineering", label: "SWFFG.SkillsNameKnowledgeEngineering", abbrev: "SWFFG.SkillsNameKnowledgeEngineering" },
  "Knowledge: Religion": { value: "Knowledge: Religion", label: "SWFFG.SkillsNameKnowledgeReligion", abbrev: "SWFFG.SkillsNameKnowledgeReligion" },
  "Knowledge: Second Impact": { value: "Knowledge: Second Impact", label: "SWFFG.SkillsNameKnowledgeSecondImpact", abbrev: "SWFFG.SkillsNameKnowledgeSecondImpact" },
};

export const skills_knowledge_stripped = {
  "Knowledge: Core Worlds": "SWFFG.SkillsNameKnowledgeCoreWorldsStripped",
  "Knowledge: Education": "SWFFG.SkillsNameKnowledgeEducationStripped",
  "Knowledge: Lore": "SWFFG.SkillsNameKnowledgeLoreStripped",
  "Knowledge: Outer Rim": "SWFFG.SkillsNameKnowledgeOuterRimStripped",
  "Knowledge: Underworld": "SWFFG.SkillsNameKnowledgeUnderworldStripped",
  "Knowledge: Warfare": "SWFFG.SkillsNameKnowledgeWarfareStripped",
  "Knowledge: Xenology": "SWFFG.SkillsNameKnowledgeXenologyStripped",
  "Knowledge: Engineering": "SWFFG.SkillsNameKnowledgeEngineeringStripped",
  "Knowledge: Religion": "SWFFG.SkillsNameKnowledgeReligionStripped",
  "Knowledge: Second Impact": "SWFFG.SkillsNameKnowledgeSecondImpactStripped"
};

export const skills_combat = {
  "Brawl": {
    value: "Brawl",
    label: "SWFFG.SkillsNameBrawl",
  },
  "Gunnery": {
    value: "Gunnery",
    label: "SWFFG.SkillsNameGunnery",
  },
  "Lightsaber": {
    value: "Lightsaber",
    label: "SWFFG.SkillsNameLightsaber",
  },
  "Melee": {
    value: "Melee",
    label: "SWFFG.SkillsNameMelee",
  },
  "Ranged: Light": {
    value: "Ranged: Light",
    label: "SWFFG.SkillsNameRangedLight",
  },
  "Ranged: Heavy": {
    value: "Ranged: Heavy",
    label: "SWFFG.SkillsNameRangedHeavy",
  },
  "Melee: Improvised": {
    value: "Melee: Improvised",
    label: "SWFFG.SkillsNameMeleeImprovised",
  },
  "Melee: Light": {
    value: "Melee: Light",
    label: "SWFFG.SkillsNameMeleeLight",
  },
  "Melee: Heavy": {
    value: "Melee: Heavy",
    label: "SWFFG.SkillsNameMeleeHeavy",
  },
  "Ranged: Improvised": {
    value: "Ranged: Improvised",
    label: "SWFFG.SkillsNameMeleeImprovised",
  },
};
